classname: pipelines.lidar_vap.pipeline.LidarVap

datastreams:
  - humboldt.buoy_z05-lidar-10m.a1

triggers: []

retriever:
  path: pipelines/lidar_vap/config/retriever.yaml

dataset:
  path: pipelines/lidar_vap/config/dataset.yaml
quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
