classname: tsdat.io.retrievers.StorageRetriever
parameters:
  transformation_parameters:
    alignment:
      time: CENTER
    width:
      time: 3600
    range:
      time: 7200

coords:
  time:
    name: N/A
    data_converters:
      - classname: tsdat.transform.CreateTimeGrid
        interval: 1hr
  height:
    name: height

data_vars:
  wind_speed:
    .*buoy_z05-lidar.*:
      name: wind_speed
      data_converters:
        - classname: tsdat.transform.BinAverage

  horizontal_dispersion:
    .*buoy_z05-lidar.*:
      name: horizontal_dispersion
      data_converters:
        - classname: tsdat.transform.BinAverage

  min_wind_speed:
    .*buoy_z05-lidar.*:
      name: min_wind_speed
      data_converters:
        - classname: tsdat.transform.BinAverage

  max_wind_speed:
    .*buoy_z05-lidar.*:
      name: max_wind_speed
      data_converters:
        - classname: tsdat.transform.BinAverage

  wind_direction:
    .*buoy_z05-lidar.*:
      name: wind_direction
      data_converters:
        - classname: tsdat.transform.BinAverage

  vertical_wind_speed:
    .*buoy_z05-lidar.*:
      name: vertical_wind_speed
      data_converters:
        - classname: tsdat.transform.BinAverage

  vertical_dispersion:
    .*buoy_z05-lidar.*:
      name: vertical_dispersion
      data_converters:
        - classname: tsdat.transform.BinAverage

  carrier_noise_ratio:
    .*buoy_z05-lidar.*:
      name: carrier_noise_ratio
      data_converters:
        - classname: tsdat.transform.BinAverage

  doppler_spectral_broadening:
    .*buoy_z05-lidar.*:
      name: doppler_spectral_broadening
      data_converters:
        - classname: tsdat.transform.BinAverage

  data_availability:
    .*buoy_z05-lidar.*:
      name: data_availability
      data_converters:
        - classname: tsdat.transform.BinAverage

  pressure:
    .*buoy_z05-lidar.*:
      name: pressure
      data_converters:
        - classname: tsdat.transform.BinAverage

  relative_humidity:
    .*buoy_z05-lidar.*:
      name: relative_humidity
      data_converters:
        - classname: tsdat.transform.BinAverage

  internal_temperature:
    .*buoy_z05-lidar.*:
      name: internal_temperature
      data_converters:
        - classname: tsdat.transform.BinAverage

  air_temperature:
    .*buoy_z05-lidar.*:
      name: air_temperature
      data_converters:
        - classname: tsdat.transform.BinAverage
